package com.sl.java00.springboot.homework.lesson10.model;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.id
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_student.name
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_student
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.id
     *
     * @return the value of tb_student.id
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    public Student withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.id
     *
     * @param id the value for tb_student.id
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_student.name
     *
     * @return the value of tb_student.name
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    public Student withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_student.name
     *
     * @param name the value for tb_student.name
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_student
     *
     * @mbg.generated Wed Nov 18 21:23:44 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append("]");
        return sb.toString();
    }
}